log:
    level: info

entryPoints:
    http:
      address: ":80"
    https:
      address: ":443"

# Docker Provider
providers:
    docker:
      endpoint: "unix:///var/run/docker.sock"
      network: "${traefik_network}"
      swarmMode: false
      exposedByDefault: false

# Enable dashboard
api:
    dashboard: true

# Let's Encrypt
certificatesResolvers:
    letsEncrypt:
      acme:
          email: "${acme_email}"
          caServer: "${lets_encrypt_env}" # Use Let's Encrypt staging server (default) when experimenting to avoid hitting Let's Encrypts rate limit
          storage: /etc/traefik/acme/acme.json
          keyType: "${lets_encrypt_keytype}"
          httpChallenge:
              # used during the challenge
              entryPoint: http
    cloudflare:
      acme:
        email: "${acme_email}"
        caServer: "${lets_encrypt_env}" # Use Let's Encrypt staging server (default) when experimenting to avoid hitting Let's Encrypts rate limit
        storage: /etc/traefik/acme/acme.json
        keyType: "${lets_encrypt_keytype}"
        dnsChallenge:
          provider: cloudflare
          delayBeforeCheck: 0
          resolvers:
            - "1.1.1.1:53"
            - "8.8.8.8:53"

accessLog: {}

metrics:
    prometheus:
        buckets:
        - 0.1
        - 0.3
        - 1.2
        - 5
        manualRouting: true